add SC improvement AIP proposal calldata
ArbitrumFoundation/governance pull request #251
Opened 2024-01-24 20:03 UTC by DZGoldman

description text lifted from https://forum.arbitrum.foundation/raw/20856

2024-01-24 20:48 UTC, godzillaba approved these changes
ran the script and got the same result, lgtm

2024-01-25 10:31 UTC, fredlacs requested changes

2024-01-25 10:31 UTC, fredlacs commented on scripts/proposals/NomineeGovV2AIP/description.txt
> +## Constitutional
```suggestion
## Constitutional
```

2024-01-25 10:31 UTC, fredlacs commented on scripts/proposals/NomineeGovV2AIP/description.txt
> +-------------------------
```suggestion
The Governance Action contract was deployed and is available for review in https://arbiscan.io/address/0xd9a2e0e5d7509f0bf1b2d33884f8c1b4d4490879#code

```

2024-01-25 10:31 UTC, fredlacs commented on scripts/proposals/NomineeGovV2AIP/nominee-gov-v2-aip.json
> +  "description": "Arbitrum | 2024-01-24 18:14:59 UTC | #1\n\n## Constitutional\n\n## Abstract\n\nThis Constitutional AIP proposes improvements to the ArbitrumDAO Constitution and the Security Council
this will get updated if we remove the heading and footer that I suggested above

2024-01-25 18:15 UTC, DZGoldman commented
forgive the force-push, I had branched off of the wrong base branch previously; should be all good now

2024-02-16 20:12 UTC, godzillaba approved these changes

2024-04-04 18:24 UTC, godzillaba approved these changes

2024-04-12 14:12 UTC, merged